name: Reusable IAC Checkov GH actions Workflow
# https://github.com/marketplace/actions/checkov-github-action
on:
  workflow_call:
    inputs:
      language:    { type: string, required: true }
      project_dir: { type: string, required: true }
      environment: { type: string, required: true }
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  generate-timestamp:
    uses: ./.github/workflows/00-generate-timestamp.yml

#####################################################################
# ===================== GitHub Action IaC Scan =====================
#####################################################################          
  github-action-iac-scan:
    runs-on: ubuntu-latest
    needs: generate-timestamp
    env:
      TIMESTAMP: ${{ needs.generate-timestamp.outputs.timestamp }}
    steps:    
      - name: Checkout Project Repository - GH actions
        uses: actions/checkout@v3

# ===================== Checkov as GitHub Action =====================
      - name: Create Checkov Scan Results Folder
        run: mkdir -p ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}

      - name: Run Checkov Scan - All Outputs
        id: checkov-all
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ inputs.project_dir }}
          framework: terraform
          output_format: cli,json,sarif
          output_file_path: ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/results_cli.txt,${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/results_json.json,${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/results_sarif.sarif
          log_level: WARNING
          container_user: 0
          # hard_fail_on: HIGH # does not work
        continue-on-error: ${{ inputs.environment == 'non-prod' }}

      - name: Rename Checkov Output Files
        run: |
          mv ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/results_json.json \
             ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/${{ inputs.language }}-IAC-Checkov-githubactions-scan-${{ inputs.environment }}-${{ env.TIMESTAMP }}.json
      
          mv ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/results_cli.txt \
             ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/${{ inputs.language }}-IAC-Checkov-githubactions-scan-${{ inputs.environment }}-${{ env.TIMESTAMP }}.log

          mv ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/results_sarif.sarif \
             ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/${{ inputs.language }}-IAC-Checkov-githubactions-scan-${{ inputs.environment }}-${{ env.TIMESTAMP }}.sarif

# ===================== Upload GH Action Checkov Output Files - Artifacts =====================
      - name: Upload Checkov GitHub Actions Scan Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}
          path: ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/
          if-no-files-found: ignore

      - name: Upload Checkov SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/${{ inputs.language }}-IAC-Checkov-githubactions-scan-${{ inputs.environment }}-${{ env.TIMESTAMP }}.sarif
