name: Reusable DAST Checkov GH actions Workflow
# https://github.com/marketplace/actions/checkov-github-action
on:
  workflow_call:
    inputs:
      dast-scan-tool: { type: string, required: true }
      language: { type: string, required: false }
      project_dir: { type: string, required: true }
      environment: { type: string, required: true }
      start_command: { type: string, required: true }
      website_target: { type: string, required: true }
#    secrets:
#      GITHUB_TOKEN: { required: false }
  workflow_dispatch:   # Allows you to run this workflow manually from the Actions tab

permissions:
  actions: read
  contents: read
  security-events: write

#####################################################################
# ===================== GitHub Action DAST Scan =====================
#####################################################################
jobs:
  ZAP-Scan:
    if: ${{ inputs.dast-scan-tool == 'zap' }}
    uses: ./.github/workflows/_21-dast-zap-workflow.yml
    with:
      dast-scan-tool: ${{ inputs.dast-scan-tool }}
#      language: ${{ inputs.language }}
      project_dir: ${{ inputs.project_dir }}
      environment: ${{ inputs.environment }}
      start_command: ${{ inputs.start_command }}
      website_target: ${{ inputs.website_target }}
